apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nodejs-login-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-login-app
  template:
    metadata:
      labels:
        app: nodejs-login-app
    spec:
      containers:
        - name: nodejs-login-app
          image: 983911888147.dkr.ecr.ap-south-1.amazonaws.com/eksrepo   # will be replaced automatically
          ports:
            - containerPort: 3000
