name: Build, Push to ECR, and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: 983911888147.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: eksrepo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Configure kubectl for EKS
        uses: aws-actions/eks-kubectl@v2
        with:
          cluster-name: ekscluster          # <-- Replace with your EKS cluster name
          region: ap-south-1

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: 983911888147.dkr.ecr.ap-south-1.amazonaws.com
          ECR_REPOSITORY: eksrepo
          IMAGE_TAG: latest
        run: |
          # Replace image in your Kubernetes manifest
          sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml
          # Apply the manifest
          kubectl apply -f k8s/deployment.yaml

