name: Build and Push to ECR

on:
  push:
    branches:
      - main   # only run when pushing to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: 983911888147.dkr.ecr.ap-south-1.amazonaws.com/eksrepo   # <-- replace with your registry
      ECR_REPOSITORY: eksrepo   # <-- replace with your ECR repo name (must match AWS console)

    steps:
      - name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: ap-south-1   # <-- REQUIRED here
    audience: sts.amazonaws.com
    output-env-credentials: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_TAG=latest
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
